### ISSUE TITLE
Instance of ClyTaggedClassGroup did not understand #exerciseName

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#378]
I was doing the Isogram exercise and tried to submit it when I got this error: `Instance of ClyTaggedClassGroup did not understand #exerciseName`. On my image Isogram is in the old format where it is a tag or sub-package under the `Exercism` package, not the new `Exercise@` format. 

I tried fetching the exercise again to see if it would upgrade it or help in some other way. Still the same problem. I think I have the latest release of the image. Do we have a way tell what release we are using?

I notice only `RPackage` and `RPackageTag` implement `#exerciseName`. Isogram was upgraded to a full package along with the others in #334. But for some reason I can't upgrade the exercise to the new format, it always reloads in the old `Exercism` package. I tried completely deleting the `Isogram` package from my image and downloading it again. Same results. I have successfully upgraded exercises before. 

![error-submitting-exercise](https://user-images.githubusercontent.com/13286932/59021167-74aa3480-889f-11e9-816f-0787a2567be9.jpg)

**Comment by bencoman** [comment]
On Thu, 6 Jun 2019 at 17:26, Samuel <notifications@github.com> wrote:

> Do we have a way tell what release we are using?
>
Not "simply" - but open Iceberg > pharo-smalltalk > Repository
and see what is the latest date and commit-hash.
Look for the date and commit-hash here ...
https://github.com/exercism/pharo-smalltalk/network

Are you able to upload the image saved at that location?

cheers -ben

**Comment by macta** [comment]
If you read the installation notes, there is a link to upgrading - https://github.com/exercism/pharo-smalltalk/blob/master/docs/UPGRADE.md

It explains it there (but may need even more work).

It won’t affect newcomers, but existing users may hit this.

Saying this - I swear I fixed that issue too, so let me look again.

Tim

**Comment by samWson** [comment]
My image is at this [commit](https://github.com/exercism/pharo-smalltalk/commit/003286a6e1837c12ec53fec9c06ada2a87779318) dated 2019-05-23 09:41.

I've upgraded the image according to the instructions in `UPGRADE.md` and now the image is at c2dbe208188c14245806f79c4e6f6a062a07c219 dated 2019-06-05 20:21. I tried fetching Isogram again but I'm still getting the same error as before.

> Are you able to upload the image saved at that location?
I'm not sure what you mean here @bencoman. Upload my image to this issue here or something else?

**Comment by bencoman** [comment]
On Fri, 7 Jun 2019 at 15:36, Samuel <notifications@github.com> wrote:

> > Are you able to upload the image saved at that location?
> I'm not sure what you mean here @bencoman <https://github.com/bencoman>.
> Upload my image to this issue here or something else?
>
> I was thinking of any third-party service, but here might do if you can
zip it under these limits.  7ZIP might provide better compression or split
file zips.
https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by macta** [comment]
Sam - are you sure you have updated your image as per the updgrade in the instructions (and maybe we have got the instructions wrong).

This does make me think, I should put some kind of version info in the baseline comment - as in looking, I’ve realised there isn’t something that would help me establish what version is in your image right now.

This sounds like the issue Roelof found weeks ago, that was fixed.

Tim

**Comment by samWson** [comment]
@macta the only thing I hadn't done on the upgrade instructions was the part right at the end: to start with a new image if all else fails. So that's what I just did. I followed our install instructions and set up a new Pharo image.

I downloaded the Isogram exercise and it was installed in the old `Exercism-Isogram` package format. I made and submitted a solution successfully. The exercism website then gave me the option of upgrading the exercise, which I did. I fetched the exercise to my image again and it was installed as `Exercise@Isogram` i.e. the new package format.

So the new image works fine and dosen't have the same bug.

@bencoman I still have the old image which had the error for downloading Isogram. I can upload it if you still want it but before I do I'd like to make sure there is no private/sensitive info in the image before I go putting it on the Internet. The only thing I should have to worry about would be the `ExercismHttpClient` class variable `ApiToken` right? I can set this to an empty string before uploading?

**Comment by macta** [comment]
So based on your description, it would seem that your old image is not loading the latest code.

Just to be sure - you are executing all the instructions (particularly the first 2 lines)?

Do you also get the prompt about load vs merge?

**Comment by samWson** [comment]
@macta This is the code I ran:
```smalltalk
'./pharo-local/iceberg/exercism' asFileReference deleteAll.
'./pharo-local/package-cache' asFileReference deleteAll.

IceRepository reset.

Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo-smalltalk/releases/latest';
 onConflict: [ :ex | ex allow ]; 
 load.
 
#ExercismManager asClass upgrade. 
```
Highlighted it all then selected `Do it and Go`.

I got several prompts about load vs merge. They were related to dirty exercise packages mostly. I clicked load on all of them.

**Comment by macta** [comment]
Hmmm I’m at a loss why that method would be missing.

The delete lines should ensure the package cache is removed to make sure you get the /latest code.

When roelof has this, it seemed to work properly (and where those delete lines came from).

As it affects a small number of users - we can direct them to a new image. I’m not sure it’s worth spending more time on.

**Comment by samWson** [comment]
> As it affects a small number of users - we can direct them to a new image. I’m not sure it’s worth spending more time on.

I'm happy with that. Everything is working fine on a new image. Closing this issue.

**Comment by macta** [comment]
Might be worth zipping up that image (and iceberg directory) in case it comes back to haunt us.

**Comment by samWson** [comment]
[pharo-smalltalk-issue-378.zip](https://github.com/exercism/pharo-smalltalk/files/3271056/pharo-smalltalk-issue-378.zip)

Here you go. I've zipped up the `Pharo.image` and `iceberg` directory from `pharo-local`. Like I said earlier I changed the `ExercismHttpClient` class variable `ApiToken` to an empty string for security.
